# Generated by Django 2.0.7 on 2018-07-14 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustoFixoMensal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('tipo', models.CharField(choices=[('BRL', 'R$ (Reais)'), ('%', '% (Porcento)')], default='BRL', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='CustoVariavelDoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentagem_de_uso', models.IntegerField(default=100)),
                ('descricao_curta', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor', models.FloatField()),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('qtd_produtos_gerados', models.IntegerField()),
                ('valor_de_venda', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='custovariaveldoproduto',
            name='insumo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_bplan.Insumo'),
        ),
        migrations.AddField(
            model_name='custovariaveldoproduto',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_bplan.Produto'),
        ),
    ]
